package com.linkang.platform.backend.meta;
// Generated 2014-11-20 18:17:03 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LkMemberUserProfile generated by hbm2java
 */
@Entity
@Table(name="LK_Member_UserProfile"
    ,catalog="lk"
    , uniqueConstraints = @UniqueConstraint(columnNames="UserName") 
)
public class LkMemberUserProfile  implements java.io.Serializable {


     private long userId;
     private Integer birthDay;
     private Integer birthMonth;
     private Integer birthYear;
     private String email;
     private String mobile;
     private String nickName;
     private long regTime;
     private String tel;
     private String userName;
     private Integer gender;
     private String userImageUrl;

    public LkMemberUserProfile() {
    }

	
    public LkMemberUserProfile(long userId, long regTime, String userName) {
        this.userId = userId;
        this.regTime = regTime;
        this.userName = userName;
    }
    public LkMemberUserProfile(long userId, Integer birthDay, Integer birthMonth, Integer birthYear, String email, String mobile, String nickName, long regTime, String tel, String userName, Integer gender, String userImageUrl) {
       this.userId = userId;
       this.birthDay = birthDay;
       this.birthMonth = birthMonth;
       this.birthYear = birthYear;
       this.email = email;
       this.mobile = mobile;
       this.nickName = nickName;
       this.regTime = regTime;
       this.tel = tel;
       this.userName = userName;
       this.gender = gender;
       this.userImageUrl = userImageUrl;
    }
   
     @Id 
    
    @Column(name="UserId", unique=true, nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    
    @Column(name="BirthDay")
    public Integer getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(Integer birthDay) {
        this.birthDay = birthDay;
    }
    
    @Column(name="BirthMonth")
    public Integer getBirthMonth() {
        return this.birthMonth;
    }
    
    public void setBirthMonth(Integer birthMonth) {
        this.birthMonth = birthMonth;
    }
    
    @Column(name="BirthYear")
    public Integer getBirthYear() {
        return this.birthYear;
    }
    
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }
    
    @Column(name="Email", length=32)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="Mobile", length=16)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="NickName", length=64)
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    
    @Column(name="RegTime", nullable=false)
    public long getRegTime() {
        return this.regTime;
    }
    
    public void setRegTime(long regTime) {
        this.regTime = regTime;
    }
    
    @Column(name="Tel", length=32)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    
    @Column(name="UserName", unique=true, nullable=false, length=128)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="Gender")
    public Integer getGender() {
        return this.gender;
    }
    
    public void setGender(Integer gender) {
        this.gender = gender;
    }
    
    @Column(name="UserImageURL", length=256)
    public String getUserImageUrl() {
        return this.userImageUrl;
    }
    
    public void setUserImageUrl(String userImageUrl) {
        this.userImageUrl = userImageUrl;
    }




}


