package com.linkang.platform.backend.meta;
// Generated 2014-11-20 18:17:03 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LkOrderForm generated by hbm2java
 */
@Entity
@Table(name="LK_OrderForm"
    ,catalog="lk"
)
public class LkOrderForm  implements java.io.Serializable {


     private long orderId;
     private long confirmTime;
     private byte orderFormState;
     private long orderTime;
     private boolean isVisible;
     private long userId;
     private long orderCartId;
     private String comment;

    public LkOrderForm() {
    }

    public LkOrderForm(long orderId, long confirmTime, byte orderFormState, long orderTime, boolean isVisible, long userId, long orderCartId, String comment) {
       this.orderId = orderId;
       this.confirmTime = confirmTime;
       this.orderFormState = orderFormState;
       this.orderTime = orderTime;
       this.isVisible = isVisible;
       this.userId = userId;
       this.orderCartId = orderCartId;
       this.comment = comment;
    }
   
     @Id 
    
    @Column(name="OrderId", unique=true, nullable=false)
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }
    
    @Column(name="ConfirmTime", nullable=false)
    public long getConfirmTime() {
        return this.confirmTime;
    }
    
    public void setConfirmTime(long confirmTime) {
        this.confirmTime = confirmTime;
    }
    
    @Column(name="OrderFormState", nullable=false)
    public byte getOrderFormState() {
        return this.orderFormState;
    }
    
    public void setOrderFormState(byte orderFormState) {
        this.orderFormState = orderFormState;
    }
    
    @Column(name="OrderTime", nullable=false)
    public long getOrderTime() {
        return this.orderTime;
    }
    
    public void setOrderTime(long orderTime) {
        this.orderTime = orderTime;
    }
    
    @Column(name="IsVisible", nullable=false)
    public boolean isIsVisible() {
        return this.isVisible;
    }
    
    public void setIsVisible(boolean isVisible) {
        this.isVisible = isVisible;
    }
    
    @Column(name="UserId", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    
    @Column(name="OrderCartId", nullable=false)
    public long getOrderCartId() {
        return this.orderCartId;
    }
    
    public void setOrderCartId(long orderCartId) {
        this.orderCartId = orderCartId;
    }
    
    @Column(name="Comment", nullable=false, length=45)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


