package com.linkang.platform.backend.meta;
// Generated 2014-11-20 18:17:03 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LkSuit generated by hbm2java
 */
@Entity
@Table(name="LK_Suit"
    ,catalog="lk"
)
public class LkSuit  implements java.io.Serializable {


     private long suitId;
     private String description;
     private String suitName;
     private Long editTime;
     private Long tijianNum;
     private Long zhushouAskNum;
     private Long zhushouPeiNum;
     private Long chuzhenNum;
     private Long yuyueLiveNum;
     private Long yuyueAskNum;

    public LkSuit() {
    }

	
    public LkSuit(long suitId, String suitName) {
        this.suitId = suitId;
        this.suitName = suitName;
    }
    public LkSuit(long suitId, String description, String suitName, Long editTime, Long tijianNum, Long zhushouAskNum, Long zhushouPeiNum, Long chuzhenNum, Long yuyueLiveNum, Long yuyueAskNum) {
       this.suitId = suitId;
       this.description = description;
       this.suitName = suitName;
       this.editTime = editTime;
       this.tijianNum = tijianNum;
       this.zhushouAskNum = zhushouAskNum;
       this.zhushouPeiNum = zhushouPeiNum;
       this.chuzhenNum = chuzhenNum;
       this.yuyueLiveNum = yuyueLiveNum;
       this.yuyueAskNum = yuyueAskNum;
    }
   
     @Id 
    
    @Column(name="SuitId", unique=true, nullable=false)
    public long getSuitId() {
        return this.suitId;
    }
    
    public void setSuitId(long suitId) {
        this.suitId = suitId;
    }
    
    @Column(name="Description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SuitName", nullable=false, length=45)
    public String getSuitName() {
        return this.suitName;
    }
    
    public void setSuitName(String suitName) {
        this.suitName = suitName;
    }
    
    @Column(name="EditTime")
    public Long getEditTime() {
        return this.editTime;
    }
    
    public void setEditTime(Long editTime) {
        this.editTime = editTime;
    }
    
    @Column(name="TijianNum")
    public Long getTijianNum() {
        return this.tijianNum;
    }
    
    public void setTijianNum(Long tijianNum) {
        this.tijianNum = tijianNum;
    }
    
    @Column(name="ZhushouAskNum")
    public Long getZhushouAskNum() {
        return this.zhushouAskNum;
    }
    
    public void setZhushouAskNum(Long zhushouAskNum) {
        this.zhushouAskNum = zhushouAskNum;
    }
    
    @Column(name="ZhushouPeiNum")
    public Long getZhushouPeiNum() {
        return this.zhushouPeiNum;
    }
    
    public void setZhushouPeiNum(Long zhushouPeiNum) {
        this.zhushouPeiNum = zhushouPeiNum;
    }
    
    @Column(name="ChuzhenNum")
    public Long getChuzhenNum() {
        return this.chuzhenNum;
    }
    
    public void setChuzhenNum(Long chuzhenNum) {
        this.chuzhenNum = chuzhenNum;
    }
    
    @Column(name="YuyueLiveNum")
    public Long getYuyueLiveNum() {
        return this.yuyueLiveNum;
    }
    
    public void setYuyueLiveNum(Long yuyueLiveNum) {
        this.yuyueLiveNum = yuyueLiveNum;
    }
    
    @Column(name="YuyueAskNum")
    public Long getYuyueAskNum() {
        return this.yuyueAskNum;
    }
    
    public void setYuyueAskNum(Long yuyueAskNum) {
        this.yuyueAskNum = yuyueAskNum;
    }




}


